import React, { useState, useEffect } from 'react';

interface MacroGeneratorProps {
  langStrings: any;
}

const MacroGenerator: React.FC<MacroGeneratorProps> = ({ langStrings }) => {
  const [scriptType, setScriptType] = useState<'attack' | 'skill' | 'antiafk'>('attack');
  const [triggerKey, setTriggerKey] = useState('F8');
  const [interval, setInterval] = useState(100);
  const [generatedScript, setGeneratedScript] = useState('');

  // Auto-update script when parameters change
  useEffect(() => {
    let script = `; Generated by ToF Assistant\n; ${langStrings.warningText}\n\n`;
    script += `#MaxThreadsPerHotkey 3\n`;
    script += `${triggerKey}::\n`;
    script += `Toggle := !Toggle\n`;
    script += `Loop\n{\n`;
    script += `    If (!Toggle)\n        Break\n`;

    if (scriptType === 'attack') {
      script += `    Send {LButton}\n`;
      script += `    Sleep ${interval}\n`;
    } else if (scriptType === 'skill') {
      script += `    Send {1}\n    Sleep 100\n`;
      script += `    Send {e}\n    Sleep 100\n`;
      script += `    Send {LButton}\n    Sleep 500\n`;
    } else if (scriptType === 'antiafk') {
      script += `    Send {Space}\n    Sleep 500\n`;
      script += `    Send {w down}\n    Sleep 200\n    Send {w up}\n`;
      script += `    Sleep ${Math.max(interval, 5000)}\n`;
    }

    script += `}\nreturn`;
    setGeneratedScript(script);
  }, [scriptType, triggerKey, interval, langStrings]);

  const handleDownload = () => {
    const blob = new Blob([generatedScript], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ToF_Macro_${scriptType}.ahk`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedScript);
  };

  return (
    <div className="flex flex-col h-full">
      {/* Warning Banner */}
      <div className="mb-6 p-4 bg-hotta-danger/10 border border-hotta-danger/30 rounded-lg flex gap-4 items-start">
        <div className="text-hotta-danger mt-1">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
        </div>
        <div>
          <h3 className="text-hotta-danger font-bold text-sm uppercase tracking-wider mb-1">
            {langStrings.warningTitle}
          </h3>
          <p className="text-xs text-hotta-text-main opacity-80 leading-relaxed">
            {langStrings.warningText}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 flex-1 min-h-0">
        {/* Controls */}
        <div className="space-y-6">
          <div className="p-5 bg-hotta-surface border border-hotta-border rounded-xl">
            <label className="block text-sm font-bold text-hotta-text-main mb-3 uppercase tracking-wider">{langStrings.scriptType}</label>
            <div className="grid grid-cols-1 gap-2">
              <button 
                onClick={() => setScriptType('attack')}
                className={`px-4 py-3 rounded-lg text-left text-sm font-mono border transition-all ${scriptType === 'attack' ? 'bg-hotta-accent/10 border-hotta-accent text-hotta-accent font-bold' : 'bg-hotta-base border-hotta-border text-hotta-text-muted hover:bg-hotta-surface-alt'}`}
              >
                {langStrings.typeAttack}
              </button>
              <button 
                onClick={() => setScriptType('skill')}
                className={`px-4 py-3 rounded-lg text-left text-sm font-mono border transition-all ${scriptType === 'skill' ? 'bg-hotta-accent/10 border-hotta-accent text-hotta-accent font-bold' : 'bg-hotta-base border-hotta-border text-hotta-text-muted hover:bg-hotta-surface-alt'}`}
              >
                {langStrings.typeSkill}
              </button>
              <button 
                onClick={() => setScriptType('antiafk')}
                className={`px-4 py-3 rounded-lg text-left text-sm font-mono border transition-all ${scriptType === 'antiafk' ? 'bg-hotta-accent/10 border-hotta-accent text-hotta-accent font-bold' : 'bg-hotta-base border-hotta-border text-hotta-text-muted hover:bg-hotta-surface-alt'}`}
              >
                {langStrings.typeAntiAfk}
              </button>
            </div>
          </div>

          <div className="p-5 bg-hotta-surface border border-hotta-border rounded-xl">
             <div className="mb-4">
                <label className="block text-xs font-bold text-hotta-text-muted mb-2 uppercase">{langStrings.keybind}</label>
                <input 
                  type="text" 
                  value={triggerKey} 
                  onChange={(e) => setTriggerKey(e.target.value.toUpperCase())}
                  className="w-full bg-hotta-base border border-hotta-border rounded px-3 py-2 text-sm font-mono text-hotta-text-main focus:border-hotta-accent focus:outline-none"
                />
             </div>
             
             <div>
                <label className="block text-xs font-bold text-hotta-text-muted mb-2 uppercase">{langStrings.interval}</label>
                <div className="flex items-center gap-4">
                    <input 
                    type="range" 
                    min="10" 
                    max="5000" 
                    step="10"
                    value={interval} 
                    onChange={(e) => setInterval(parseInt(e.target.value))}
                    className="flex-1 accent-hotta-accent h-2 bg-hotta-base rounded-lg appearance-none cursor-pointer"
                    />
                    <span className="w-16 text-right font-mono text-hotta-accent font-bold text-sm">{interval}ms</span>
                </div>
             </div>
          </div>

          <div className="p-4 bg-hotta-highlight/10 border border-hotta-highlight/20 rounded-lg text-xs text-hotta-text-main leading-relaxed font-mono">
            {langStrings.instruction}
          </div>
        </div>

        {/* Preview */}
        <div className="flex flex-col h-full bg-hotta-surface border border-hotta-border rounded-xl overflow-hidden shadow-lg">
           <div className="px-4 py-3 border-b border-hotta-border bg-hotta-base flex justify-between items-center">
              <h4 className="text-xs font-bold font-display text-hotta-text-muted uppercase tracking-wider">{langStrings.preview}</h4>
              <div className="flex gap-2">
                 <button onClick={handleCopy} className="text-xs text-hotta-accent hover:text-white px-2 py-1 rounded hover:bg-hotta-accent transition-colors">{langStrings.copyClipboard}</button>
              </div>
           </div>
           <div className="flex-1 bg-[#1e1e1e] p-4 overflow-auto">
              <pre className="font-mono text-xs text-green-400 whitespace-pre-wrap">
                {generatedScript}
              </pre>
           </div>
           <div className="p-4 border-t border-hotta-border bg-hotta-surface-alt">
              <button 
                onClick={handleDownload}
                className="w-full py-3 bg-hotta-accent text-white font-bold font-display tracking-wider rounded-lg hover:bg-cyan-400 transition-colors shadow-lg shadow-hotta-accent/20 flex items-center justify-center gap-2"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
                {langStrings.downloadAhk}
              </button>
           </div>
        </div>
      </div>
    </div>
  );
};

export default MacroGenerator;